{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
{{- if eq .Values.metrics.enabled true -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}-pm-allow
  labels: {{- include "eric-ctrl-bro.labels" . | nindent 4 }}
  annotations: {{- include "eric-ctrl-bro.annotations" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-ctrl-bro.name" . }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app.kubernetes.io/name: {{ .Values.pm.host }}
    ports:
    - protocol: TCP
      port: {{ template "eric-ctrl-bro.metrics.server.port" . }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}