apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "eric-test-service-basic.serviceAccountName" . }}
  labels:
{{ include "eric-test-service-basic.k8sLabels" . | indent 4 }}
  annotations:
{{ include "eric-test-service-basic.prodInfoAnnotations" . | indent 4 }}