{{- if .Values.tags.pm }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ index .Values "eric-pm-server" "clusterRoleName"  | quote  }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ index .Values "eric-pm-server" "clusterRoleName"  | quote  }}
subjects:
- kind: ServiceAccount
  name: {{ index .Values "eric-pm-server" "server" "serviceAccountName"  | quote  }}
  namespace: {{ .Release.Namespace }}
{{- end }}
