apiVersion: v1
kind: Service
metadata:
  name: {{ template "eric-ctrl-bro.name" . }}
  annotations: {{- include "eric-ctrl-bro.annotations" . | nindent 4 }}
  labels: {{- include "eric-ctrl-bro.labels" . | nindent 4 }}
spec:
  {{- include "eric-ctrl-bro.internalIPFamilyAndPolicy" . | trim | nindent 2 }}
  type: ClusterIP
  ports:
  {{- if or (eq (include "eric-ctrl-bro.globalSecurity" .) "false") (eq .Values.service.endpoints.restActions.tls.enforced "optional") }}
  - name: http
    port: {{ .Values.bro.restPort }}
  {{- end }}
  - name: grpc
    port: {{template "eric-ctrl-bro.globalBroGrpcServicePort" .}}
  {{- if and (eq .Values.metrics.enabled true) (ne (include "eric-ctrl-bro.metrics.server.port" . | quote) (.Values.bro.restPort | quote)) }}
  - name: {{ template "eric-ctrl-bro.metrics.server.name" . }}
    port: {{ template "eric-ctrl-bro.metrics.server.port" . }}
  {{- end }}
  {{- if eq (include "eric-ctrl-bro.globalSecurity" .) "true" }}
  - name: https
    port: {{ .Values.bro.restTlsPort }}
  {{- if eq .Values.bro.enableConfigurationManagement true }}
  - name: cmm-tls
    port: {{.Values.bro.cmmNotifTlsPort}}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ template "eric-ctrl-bro.name" . }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
