zapConfig:
  baseUrl: "http://eric-ctrl-bro:7001"
  scanType: "full"
  config_dir: "zap/config"
  globalConfig:
  - id: "10106"
    action: "IGNORE"
    message: "The site is only served under HTTP and not HTTPS."
  - id: "90028"
    action: "IGNORE"
    message: "The insecure HTTP method [DELETE] is enabled on the web server for this resource"
  endpoints:
  - name: "bro-health-endpoint"
    url: "/v1/health/"
  - name: "bro-backup-endpoint"
    url: "/v1/backup-manager/DEFAULT/backup"
  - name: "bro-backup-id-endpoint"
    url: "/v1/backup-manager/DEFAULT/backup/bu1"
  - name: "bro-action-endpoint"
    url: "/v1/backup-manager/DEFAULT/action"
  - name: "bro-action-id-endpoint"
    url: "/v1/backup-manager/DEFAULT/action/100"
  - name: "bro-backup-manager"
    url: "/v1/backup-manager/"
  - name: "bro-backup-manager-default"
    url: "/v1/backup-manager/DEFAULT/"
  - name: "v2-brm-create-backup"
    url: "/v2/ericsson-brm:brm::backup-manager::create-backup"
  - name: "v2-brm-delete-backup"
    url: "/v2/ericsson-brm:brm::backup-manager::delete-backup"
  - name: "v2-brm-import-backup"
    url: "/v2/ericsson-brm:brm::backup-manager::import-backup"
  - name: "v2-brm-export-backup"
    url: "/v2/ericsson-brm:brm::backup-manager::backup::export"
  - name: "v2-brm-restore-backup"
    url: "/v2/ericsson-brm:brm::backup-manager::backup::restore"
  - name: "v3-housekeeping"
    url: "/v3/backup-managers/DEFAULT/housekeeping/"
  - name: "v3-bro-scheduler"
    url: "/v3/backup-managers/DEFAULT/scheduler"
  - name: "v3-bro-scheduler-configuration"
    url: "/v3/backup-managers/DEFAULT/scheduler/configuration"
  - name: "v3-bro-scheduler-periodic-events"
    url: "/v3/backup-managers/DEFAULT/scheduler/periodic-events"
  - name: "v3-bro-scheduler-periodic-events-id"
    url: "/v3/backup-managers/DEFAULT/scheduler/periodic-events/100"
  - name: "v4-bro-health-endpoint"
    url: "/v4/health"
  - name: "v4-bro-backup-managers"
    url: "/v4/backup-managers"
  - name: "v4-bro-backup-managers-default"
    url: "/v4/backup-managers/DEFAULT"
  - name: "v4-bro-backup-managers-default-agents"
    url: "/v4/backup-managers/DEFAULT/agents"
  - name: "v4-bro-backups-endpoint"
    url: "/v4/backup-managers/DEFAULT/backups"
  - name: "v4-bro-backups-id-endpoint"
    url: "/v4/backup-managers/DEFAULT/backups/myBackup"
  - name: "v4-bro-last-task"
    url: "/v4/backup-managers/DEFAULT/last-task"
  - name: "v4-bro-imports"
    url: "/v4/backup-managers/DEFAULT/imports"
  - name: "v4-imports-id"
    url: "/v4/backup-managers/DEFAULT/imports/100"
  - name: "v4-bro-exports"
    url: "/v4/backup-managers/DEFAULT/backups/<backup-id>/exports"
  - name: "v4-bro-exports-id"
    url: "/v4/backup-managers/DEFAULT/backups/<backup-id>/exports/100"
  - name: "v4-bro-backups-restores"
    url: "/v4/backup-managers/DEFAULT/backups/<backup-id>/restores"
  - name: "v4-bro-backups-restores-id"
    url: "/v4/backup-managers/DEFAULT/backups/<backup-id>/restores/100"
  - name: "v4-bro-configuration-housekeeping"
    url: "/v4/backup-managers/DEFAULT/configuration/housekeeping"
  - name: "v4-bro-configuration-scheduling"
    url: "/v4/backup-managers/DEFAULT/configuration/scheduling"
  - name: "v4-bro-periodic-schedules"
    url: "/v4/backup-managers/DEFAULT/periodic-schedules"
  - name: "v4-bro-calendar-schedules"
    url: "/v4/backup-managers/DEFAULT/calendar-schedules"
  - name: "v4-bro-periodic-schedules-id"
    url: "/v4/backup-managers/DEFAULT/periodic-schedules/100"
  report:
    dir: "zap/reports"
    format:
    - html
    - json
