repository: eridoca
# ADP Reference Microservice folder:
folderId: 0b004cffc1b15332
documents:
  - title: "Backup and Restore Orchestrator User Guide"
    file: "./build/service/Documentation/markdown/user-guide/user_guide.pdf"
    source_files:
      - "./service/Documentation/BackupAndRestoreOrchestrator_User_Guide/user_guide.md"
      - "./service/Documentation/BackupAndRestoreOrchestrator_User_Guide/architecture.png"
      - "./service/Documentation/BackupAndRestoreOrchestrator_User_Guide/fragments/.generated/pm_metrics.md"
      - "./service/Documentation/BackupAndRestoreOrchestrator_User_Guide/fragments/.generated/service_ports.md"
    decimal-class: "1553"
    class-prefix: "1"
    individual-number: "APR 201 40/10"
    eri_document_type: "User Guide"
    lang: "en"
    format: "pdf"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator Agent Implementation Guide"
    file: "./build/service/Documentation/BackupAndRestoreOrchestrator_Agent_Implementation_Guide/BackupAndRestoreOrchestrator_Agent_Implementation_Guide.sdif"
    source_files:
      - "./service/Documentation/BackupAndRestoreOrchestrator_Agent_Implementation_Guide/BackupAndRestoreOrchestrator_Agent_Implementation_Guide.txt"
    decimal-class: "198 17"
    class-prefix: "1"
    individual-number: "APR 201 40/10"
    eri_document_type: "User Guide"
    lang: "en"
    format: "sdif"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator Operations Guide"
    file: "./build/service/Documentation/BackupAndRestoreOrchestrator_Operations_Guide/BackupAndRestoreOrchestrator_Operations_Guide.sdif"
    source_files:
      - "./service/Documentation/BackupAndRestoreOrchestrator_Operations_Guide/BackupAndRestoreOrchestrator_Operations_Guide.txt"
    decimal-class: "198 17"
    class-prefix: "2"
    individual-number: "APR 201 40/10"
    eri_document_type: "User Guide"
    lang: "en"
    format: "sdif"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator Operations Guide CMYP"
    file: "./build/service/Documentation/BackupAndRestoreOrchestrator_Operations_Guide_CMYP/BackupAndRestoreOrchestrator_Operations_Guide_CMYP.sdif"
    source_files:
      - "./service/Documentation/BackupAndRestoreOrchestrator_Operations_Guide_CMYP/BackupAndRestoreOrchestrator_Operations_Guide_CMYP.txt"
    decimal-class: "198 17"
    class-prefix: "5"
    individual-number: "APR 201 40/10"
    eri_document_type: "User Guide"
    lang: "en"
    format: "sdif"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator Rest Specification v4"
    file: "./service/SupportingDocumentation/rest_specification_v4.html"
    source_files:
      - "./service/SupportingDocumentation/v4_spec.yaml"
    decimal-class: "155 19"
    class-prefix: "3"
    individual-number: "CAF 101 027/10"
    eri_document_type: "Interface Description"
    lang: "en"
    format: "html"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator Rest Specification"
    file: "./service/SupportingDocumentation/rest_specification_v1v3.html"
    source_files:
      - "./service/SupportingDocumentation/rest_specification.raml"
    decimal-class: "155 19"
    class-prefix: "2"
    individual-number: "CAF 101 027/10"
    eri_document_type: "Interface Description"
    lang: "en"
    format: "html"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator - GRPC API User Guide"
    file: "./build/service/Documentation/BackupAndRestoreOrchestrator_Grpc_API_User_Guide/BackupAndRestoreOrchestrator_Grpc_API_User_Guide.sdif"
    source_files:
      - "./service/Documentation/BackupAndRestoreOrchestrator_Grpc_API_User_Guide/BackupAndRestoreOrchestrator_Grpc_API_User_Guide.txt"
    decimal-class: "198 17"
    class-prefix: "4"
    individual-number: "APR 201 40/10"
    eri_document_type: "User Guide"
    lang: "en"
    format: "sdif"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator - GRPC API Specification"
    file: "./build/service/Documentation/BackupAndRestoreOrchestrator_Grpc_Specification/BackupAndRestoreOrchestrator_Grpc_Specification.sdif"
    source_files:
      - "./service/Documentation/BackupAndRestoreOrchestrator_Grpc_Specification/BackupAndRestoreOrchestrator_Grpc_Specification.txt"
    decimal-class: "155 19"
    class-prefix: "1"
    individual-number: "CAF 101 026/10"
    eri_document_type: "Interface Description"
    lang: "en"
    format: "sdif"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator Rest API User Guide"
    file: "./build/service/Documentation/BackupAndRestoreOrchestrator_Rest_API_User_Guide/BackupAndRestoreOrchestrator_Rest_API_User_Guide.sdif"
    source_files:
      - "./service/Documentation/BackupAndRestoreOrchestrator_Rest_API_User_Guide/BackupAndRestoreOrchestrator_Rest_API_User_Guide.txt"
    decimal-class: "198 17"
    class-prefix: "3"
    individual-number: "APR 201 40/10"
    eri_document_type: "User Guide"
    lang: "en"
    format: "sdif"
    eri_doc_responsible: "BDGS SA OSS"
  - title: "Backup and Restore Orchestrator Characteristics Summary Report {semver}"
    file: "./characteristics_report.pdf"
    source_files:
      - "./characteristics_report.pdf"
    decimal-class: "152 83"
    class-prefix: "2"
    individual-number: "APR 201 40/10"
    strategy: "ordinal"
    eri_document_type: "Test Report"
    lang: "en"
    format: "pdf"
    eri_doc_responsible: "BDGS SA OSS"
